version: '3'
services:
  web:
    container_name: shiny-octo-guacamole
    build: .
    ports:
     - "3000:3000"
    volumes:
     - ./:/app
     - /app/node_modules
    restart: always
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'anshu'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./data/db:/var/lib/mysql